server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authuser-service
              uri: lb://EAD-AUTHUSER-SERVICE
              predicates:
                - Path=/ead-authuser/**
              filters:
                - StripPrefix=1

            - id: course-service
              uri: lb://EAD-COURSE-SERVICE
              predicates:
                - Path=/ead-course/**
              filters:
                - StripPrefix=1
          discovery:
            locator:
              enabled: true  # Ativando o Discovery Locator

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
