apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Herdar da base
resources:
  - ../../base

# Patches para staging
patchesStrategicMerge:
  - patches.yaml

# Nome único para evitar conflitos
nameSuffix: -staging
